test_that("[T01 T14 T16 T24 T33 T35 T36 T37 T38 T40 T42 T55 T60] fixed-split example is executable and exact", {
  path <- testthat::test_path("..", "..", "exemplars", "predictive-geometry", "fixed-split.R")
  skip_if_not(file.exists(path), "Source-tree exemplar is not installed with test files")
  env <- new.env(parent = globalenv())
  output <- capture.output(sys.source(path, env))
  expect_match(paste(output, collapse = "\n"), "squared geometry units")
  expect_match(paste(output, collapse = "\n"), "Training/evaluation: 2/2")
  expect_equal(env$mode_evidence$gain, c(4, -1), tolerance = 1e-11)
  expect_equal(env$evidence$table$gain, 3, tolerance = 1e-11)
  expect_identical(env$zero$table$gain, 0)
  values <- lapply(env$fits, pg_forms)
  for (value in values[-1L]) expect_equal(value, values[[1L]], tolerance = 1e-11)
  for (score in env$scores[-1L]) expect_equal(as.data.frame(score), as.data.frame(env$scores[[1L]]), tolerance = 1e-11)
  expect_false(any(grepl("explained|standard_error", names(env$evidence$table))))
})
test_that("[T55 T60] the public vignette executes its numerical and refusal claims", {
  path <- testthat::test_path("..", "..", "vignettes", "predictive-geometry.Rmd")
  skip_if_not(file.exists(path), "Source vignette is checked separately in installed packages")
  skip_if_not_installed("knitr")
  script <- tempfile(fileext = ".R")
  on.exit(unlink(script), add = TRUE)
  knitr::purl(path, output = script, documentation = 0, quiet = TRUE)
  env <- new.env(parent = globalenv())
  invisible(capture.output(sys.source(script, env)))
  expect_equal(env$evidence$table$gain, 3, tolerance = 1e-11)
  expect_equal(env$modes$gain, c(4, -1), tolerance = 1e-11)
  expect_identical(env$overlap$reasons[[1]], "overlapping_training_evaluation_origins")
})
