// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fused_pair_difference_atoms_cpp
Rcpp::NumericMatrix fused_pair_difference_atoms_cpp(const Rcpp::List& left_blocks, const Rcpp::List& right_blocks, const Rcpp::IntegerVector& left_index, const Rcpp::IntegerVector& right_index, const Rcpp::NumericVector& edge_weight, const Rcpp::IntegerVector& pair_left, const Rcpp::IntegerVector& pair_right);
RcppExport SEXP _crossform_fused_pair_difference_atoms_cpp(SEXP left_blocksSEXP, SEXP right_blocksSEXP, SEXP left_indexSEXP, SEXP right_indexSEXP, SEXP edge_weightSEXP, SEXP pair_leftSEXP, SEXP pair_rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type left_blocks(left_blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type right_blocks(right_blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type left_index(left_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type right_index(right_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type edge_weight(edge_weightSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pair_left(pair_leftSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pair_right(pair_rightSEXP);
    rcpp_result_gen = Rcpp::wrap(fused_pair_difference_atoms_cpp(left_blocks, right_blocks, left_index, right_index, edge_weight, pair_left, pair_right));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crossform_fused_pair_difference_atoms_cpp", (DL_FUNC) &_crossform_fused_pair_difference_atoms_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_crossform(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
