# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fused_pair_difference_atoms_cpp <- function(left_blocks, right_blocks, left_index, right_index, edge_weight, pair_left, pair_right) {
    .Call(`_crossform_fused_pair_difference_atoms_cpp`, left_blocks, right_blocks, left_index, right_index, edge_weight, pair_left, pair_right)
}

